export let datos_articulos = [
            { 
            id:1,
            titulo: "Titulo 1",
            imagen: "./../../imagenes/imagen1.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"},
            { id:2,titulo: "Titulo 2",
            imagen: "./../../imagenes/imagen2.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"},
            { id:3,titulo: "Titulo 3",
            imagen: "./../../imagenes/imagen3.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"},
            { id:4,titulo: "Titulo 4",
            imagen: "./../../imagenes/imagen4.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"},
            { id:5,titulo: "Titulo 5",
            imagen: "./../../imagenes/imagen5.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"},
            { id:6,titulo: "Titulo 6",
            imagen: "./../../imagenes/imagen6.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"},
            { id:7,titulo: "Titulo 7",
            imagen: "./../../imagenes/imagen7.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"},
            { id:8,titulo: "Titulo 8",
            imagen: "./../../imagenes/imagen8.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"},
            { id:9,titulo: "Titulo 9",
            imagen: "./../../imagenes/imagen9.jpg",
            parrafo: "Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.",
            fecha: "22/01/22"}
];